### ISSUE TITLE
Blanca Estela Valerio

### ISSUE THREAD

**Issue by Blanca-estela-valerio-rivero** [SistemasTecTlaxiaco/actividad-7-Blanca-estela-valerio-rivero#1]
[Linea de la WEB.pdf](https://github.com/SistemasTecTlaxiaco/actividad-7-Blanca-estela-valerio-rivero/files/9852887/Linea.de.la.WEB.pdf)

**Comment by AmeliReyesHernandez** [comment]
19.4

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
